FROM rust:1.91-alpine AS builder
WORKDIR /app
RUN apk add openssl-dev openssl-libs-static pkgconfig
COPY . .
RUN --mount=type=cache,target=/app/target \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build && \
    cp ./target/debug/backend ./backend
CMD ./backend
