# Stage 1: Build the application
FROM rust:1.91 AS builder
WORKDIR /app
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    pkg-config && \
    rm -rf /var/lib/apt/lists/*
COPY . .
RUN --mount=type=cache,target=/app/target \
    --mount=type=cache,target=/usr/local/cargo/git/db \
    --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build --features testing && \
    cp target/debug/backend ./backend

# Stage 2: Create the final runtime image
FROM gcr.io/distroless/cc-debian12 AS runtime
COPY --from=builder /app/backend /app/test
EXPOSE 8080
ENTRYPOINT ["/app/test"]
