name: Test and deploy

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: test_user
      DB_PASS: mypassword
      SMTP_SERVER: ${{ vars.SMTP_SERVER }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
      SERVER_NAME: 127.0.0.1
      SSL_OWNER_EMAIL: ""

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build tests
      run: make build_test

    - name: Run tests
      run: make test

  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push production
      run: |
        make build_production_https &&
        echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u dadencukillia --password-stdin && \
        docker push ghcr.io/dadencukillia/pupsiks:backend && \
        docker push ghcr.io/dadencukillia/pupsiks:frontend && \
        docker push ghcr.io/dadencukillia/pupsiks:emailworker

  deploy:
    needs: [test, build_and_push]
    runs-on: self-hosted
    environment: production
    concurrency: production
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      SMTP_SERVER: ${{ vars.SMTP_SERVER }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SERVER_NAME: ${{ vars.SERVER_NAME }}
      SSL_OWNER_EMAIL: ${{ vars.SSL_OWNER_EMAIL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "SERVER_NAME=${{ vars.SERVER_NAME }}" >> .env
        echo "SSL_OWNER_EMAIL=${{ vars.SSL_OWNER_EMAIL }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
        echo "SMTP_SERVER=${{ vars.SMTP_SERVER }}" >> .env
        echo "SMTP_PORT=${{ vars.SMTP_PORT }}" >> .env
        echo "SMTP_SENDER=${{ secrets.SMTP_SENDER }}" >> .env
        echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env

    - name: Runtime
      run: |
        echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u dadencukillia --password-stdin && \
        make production_https

    - name: Restart Nginx # After containers update Nginx is able to send 502 status code
      run: docker compose exec nginx sh -c "nginx -s reload"
